[project]
name = "comfyui-white-extractor"
version = "0.0.2"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"

[project.urls]
repository = "https://github.com/duchamps0305/comfyui-white-extractor"

